### ISSUE TITLE
Vertaisarviointi 2

### ISSUE THREAD

**Issue by pllk** [EssiPry/sewing-pattern-library#2]
Käyttökokemus

* Sovellus on tyylikäs ja siitä tulee ammattimainen vaikutelma.
* Pystyin lähettämään tyhjän kommentin arvioon, tämän voisi estää.
* Löysin mahdollisuuden lähettää uuden mallin vain hakutoiminnon kautta, tämä voisi olla selkeämmin esillä.

Tekniset asiat

* Tekninen toteutus on hyvin tehty mutta sitä voi vielä hioa.
* Kun koodissa on rivinvaihto, yksi rivinvaihto riittää. Nyt tiedostossa `app.py` on kaksi rivinvaihtoa (rivit 3-4 ja 7-8).
* Virheenkäsittely try-catch ei ole tarpeen, jos SQL-komennon pitäisi onnistua aina (näin pitäisi olla monissa komennoissa sovelluksessasi).
* Kysely muotoa `SELECT *` ei ole suositeltava vaan olisi aina hyvä antaa sarakkeet, jotka haetaan.
* Yleensä on tapana kirjoittaa `COUNT(*)` eikä `COUNT (*)`.
* Tiedoston `routes.py` funktiossa `register` nimet `password1` ja `password_conf` ovat vaikeasti ymmärrettäviä.
* Tiedostossa `routes.py` riveillä 51-54 lukijalle ei ole selvää, miksi tyhjä hakusana korvataan prosentilla. Onko tämä tarpeen?
* Pitkissä funktioissa olisi hyvä laittaa sopivasti rivinvaihtoja luettavuuden parantamiseksi.
* Varmista, että koodissa ei ole ylimääräisiä tulostuksia (huomasin tiedostossa `routes.py` riveillä 112, 114 ja 127).

**Comment by EssiPry** [comment]
Kiitos @pllk hyvistä huomioista ja kattavasta palautteesta! Näitä ihmettelemään seuraavaksi :)
